### ISSUE TITLE
"python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by SamCullin** [barnumbirr/coinmarketcap#39]
I have started to get this error when I do a pip install

**Comment by barnumbirr** [comment]
Hello,

I'm gonna need more information before I'm able to help you:
- What Python version are you using?
- Which coinmarketcap library are you trying to install?
- Do you already have an older version of the coinmarketcap library installed? If so, which version?

Cheers.

**Comment by moonloom** [comment]
I am having the same issue. Using python 3.6.3 in venv. I am just using "pip install coinmarketcap". I do not already have the coinmarketcap module.

**Comment by barnumbirr** [comment]
Can you please make sure you're using the latest versions of the following tools:

* pip (v.10.0.1)
* setuptools (39.1.0)

I just tried a clean install on Python 3.6.5 without any issues:

```bash
[user@hostname ~]$ pip3 install coinmarketcap
Collecting coinmarketcap
Collecting requests-cache==0.4.13 (from coinmarketcap)
  Using cached https://files.pythonhosted.org/packages/00/62/9e45a38988cb48c474805a1626439f4d9a486a042bd077af888fa8b17a64/requests_cache-0.4.13-py2.py3-none-any.whl
Collecting requests==2.18.4 (from coinmarketcap)
  Using cached https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.4->coinmarketcap)
  Using cached https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.18.4->coinmarketcap)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests==2.18.4->coinmarketcap)
  Using cached https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.4->coinmarketcap)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: urllib3, certifi, idna, chardet, requests, requests-cache, coinmarketcap
Successfully installed certifi-2018.4.16 chardet-3.0.4 coinmarketcap-5.0.1 idna-2.6 requests-2.18.4 requests-cache-0.4.13 urllib3-1.22
```

Cheers.

**Comment by SamCullin** [comment]
Hi,

I updated my anaconda and the error has not persisted. I will withdraw my
issue but if you are still interested in the issue I can find out the
version of anaconda I was previously on. The error had something to do with
decoding asiic. I had the older version and the error occurred when I what
trying to update.

Regards
Sam

**Comment by Alocaly** [comment]
Hey !!

I've just had the same issue, here the text :
"Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    long_description = open('README.md','r').read(),
  File "d:\tools\Anaconda3\envs\FreqTradeCcxt\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6490: character maps to <undefined>"

it's a region / page encoding issue on Windows ( I'm french, so using cp1512 )

I solved this issue by changing the opening in the setup file :
long_description = open('README.md', 'r', encoding="utf8").read(),

And forcing utf8 for opening, and it worked ok

**Comment by barnumbirr** [comment]
Hey @Alocaly,

thanks for looking into this. There's a small issue though: ```open(encoding='utf8')``` is Python 3 only so I'll have to figure out a way to force file encoding gracefully for both Python versions.

I could probably get away with just using ```io.open()``` as only Python 2.7 and 3.6 are supported by the library so the ```io``` performance issues in Py2.6 and 3.0 wouldn't really be a problem.

I'm open to suggestions if anyone has a better idea 😉 

Cheers.

**Comment by barnumbirr** [comment]
Should be fixed in v.5.0.2 / d9e200d10cc61d8ca428f616d9063c3778bf1fc2.
