### ISSUE TITLE
Very very long answer

### ISSUE THREAD

**Issue by Michelgard** [barnumbirr/coinmarketcap#42]
Hello, I am under Debian8 and the answer is very long to come (about 1mn) ...

**Comment by barnumbirr** [comment]
I'm going to need more info:

- what version of Python are you using?
- what version of the library are you using?

Cheers.

**Comment by Michelgard** [comment]
what version of Python are you using?  2.7.9 
what version of the library are you using? 5.0.3

**Comment by barnumbirr** [comment]
Hmmm, I don't seem to run into any performance issues. Running the following code takes around 590ms.

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import time
from coinmarketcap import Market

def timing(f):
    def wrap(*args):
        time1 = time.time()
        ret = f(*args)
        time2 = time.time()
        print '%s function took %0.3f ms' % (f.func_name, (time2-time1)*1000.0)
        return ret
    return wrap

@timing
def do_work():
    coinmarketcap = Market()
    print coinmarketcap.ticker(start=0, limit=3, convert='EUR')

if __name__ == '__main__':
    do_work()
```

Can you try this out and tell me how long this takes for you?

Cheers.

**Comment by Michelgard** [comment]
Hello,
Thanks for the test code.
Actually I must have a problem on my server because I have: do_work function took 150902.367 ms
I tested on another server and there: do_work function took 101.653 ms

On the other hand on the 1st server the call of the API in PHP is very fast ... so I have to see a problem rated Python.

Cheers.

**Comment by Michelgard** [comment]
Yes thank you very much
