### ISSUE TITLE
Ticket Result Limit - 100?

### ISSUE THREAD

**Issue by theMoe** [barnumbirr/coinmarketcap#44]
Hi,

with API v2 the ticker request got a result limit of 100. Why? I would like to have one request for all currencies.

Best regards,

Moe

**Comment by barnumbirr** [comment]
Hello,

that behaviour is defined by coinmarketcap.com themselves and there's not really a whole lot we can do about it unfortunately:

```
(int) limit - return a maximum of [limit] results (default is 100; max is 100)
```

Cheers
