### ISSUE TITLE
Get multiple ids in ticker

### ISSUE THREAD

**Issue by amiut** [barnumbirr/coinmarketcap#45]
I need to search through currencies so here's what i do  : 
Let's say the user enters the word "bit", First i get the ids of the searched currency with `listing` endpoint, now i want to get list of those coins but there's no way to do this according to the documentation since `ticker/{id}` gives data only for 1 currency. is there any other way to do this?

**Comment by barnumbirr** [comment]
Hello,

there's no other way of doing what you're trying to do. This is a limitation of the coinmarketcap API, not of the library.

Cheers.
